apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: attacker
  name: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
      - image: kubearmor/ubuntu-w-utils:0.1
        name: attacker
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
