apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-web-protect
spec:
  action: Allow
  file:
    matchDirectories:
    - dir: /
      recursive: true
  process:
    matchDirectories:
    - dir: /usr/sbin/
      recursive: true
    matchPaths:
    - path: /bin/dash
    - path: /bin/ping
  selector:
    matchLabels:
      tier: frontend
      app: dvwa-web
  severity: 1
---
